application: bmalayiids
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
    
- url: /.*
  script: genenames.py
  login: required
